package modelo;
// Generated 06/01/2015 02:52:24 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name="administrador"
    ,catalog="restaurant"
)
public class Administrador  implements java.io.Serializable {


     private int idAdministrador;
     private String nombreAdministrador;
     private String apellidoAdministrador;
     private String direccionAdministrador;
     private Integer edad;

    public Administrador() {
    }

	
    public Administrador(int idAdministrador) {
        this.idAdministrador = idAdministrador;
    }
    public Administrador(int idAdministrador, String nombreAdministrador, String apellidoAdministrador, String direccionAdministrador, Integer edad) {
       this.idAdministrador = idAdministrador;
       this.nombreAdministrador = nombreAdministrador;
       this.apellidoAdministrador = apellidoAdministrador;
       this.direccionAdministrador = direccionAdministrador;
       this.edad = edad;
    }
   
     @Id 

    
    @Column(name="Id_administrador", unique=true, nullable=false)
    public int getIdAdministrador() {
        return this.idAdministrador;
    }
    
    public void setIdAdministrador(int idAdministrador) {
        this.idAdministrador = idAdministrador;
    }

    
    @Column(name="nombre_administrador", length=20)
    public String getNombreAdministrador() {
        return this.nombreAdministrador;
    }
    
    public void setNombreAdministrador(String nombreAdministrador) {
        this.nombreAdministrador = nombreAdministrador;
    }

    
    @Column(name="apellido_administrador", length=20)
    public String getApellidoAdministrador() {
        return this.apellidoAdministrador;
    }
    
    public void setApellidoAdministrador(String apellidoAdministrador) {
        this.apellidoAdministrador = apellidoAdministrador;
    }

    
    @Column(name="direccion_administrador", length=20)
    public String getDireccionAdministrador() {
        return this.direccionAdministrador;
    }
    
    public void setDireccionAdministrador(String direccionAdministrador) {
        this.direccionAdministrador = direccionAdministrador;
    }

    
    @Column(name="edad")
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }




}


