package modelo;
// Generated 06/01/2015 02:52:24 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cartilla generated by hbm2java
 */
@Entity
@Table(name="cartilla"
    ,catalog="restaurant"
)
public class Cartilla  implements java.io.Serializable {


     private int idCartilla;
     private String nombrePlato;
     private String nombreEntrada;
     private String nombrePostre;
     private Float precio;
     private String descripcion;
     private String ingredientes;

    public Cartilla() {
    }

	
    public Cartilla(int idCartilla) {
        this.idCartilla = idCartilla;
    }
    public Cartilla(int idCartilla, String nombrePlato, String nombreEntrada, String nombrePostre, Float precio, String descripcion, String ingredientes) {
       this.idCartilla = idCartilla;
       this.nombrePlato = nombrePlato;
       this.nombreEntrada = nombreEntrada;
       this.nombrePostre = nombrePostre;
       this.precio = precio;
       this.descripcion = descripcion;
       this.ingredientes = ingredientes;
    }
   
     @Id 

    
    @Column(name="Id_cartilla", unique=true, nullable=false)
    public int getIdCartilla() {
        return this.idCartilla;
    }
    
    public void setIdCartilla(int idCartilla) {
        this.idCartilla = idCartilla;
    }

    
    @Column(name="nombre_plato", length=40)
    public String getNombrePlato() {
        return this.nombrePlato;
    }
    
    public void setNombrePlato(String nombrePlato) {
        this.nombrePlato = nombrePlato;
    }

    
    @Column(name="nombre_entrada", length=40)
    public String getNombreEntrada() {
        return this.nombreEntrada;
    }
    
    public void setNombreEntrada(String nombreEntrada) {
        this.nombreEntrada = nombreEntrada;
    }

    
    @Column(name="nombre_postre", length=20)
    public String getNombrePostre() {
        return this.nombrePostre;
    }
    
    public void setNombrePostre(String nombrePostre) {
        this.nombrePostre = nombrePostre;
    }

    
    @Column(name="precio", precision=12, scale=0)
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }

    
    @Column(name="descripcion", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="ingredientes", length=200)
    public String getIngredientes() {
        return this.ingredientes;
    }
    
    public void setIngredientes(String ingredientes) {
        this.ingredientes = ingredientes;
    }




}


